spring.application.name=newadmission
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#databaseconfiguration
#spring.datasource.url=jdbc:mysql://pjsofttech-db-2.cri6eu8uc7zv.ap-south-1.rds.amazonaws.com:3306/pjsofttech?ServerTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=pjsofttechAWS
#server.port:46443
#server.ssl.key-store=/etc/letsencrypt/live/pjsofttech.in/pjsofttech.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=pjsofttech.in
#server.ssl.enabled=true
#client.superadmin.base-url=https://pjsofttech.in:43443

#----------------------------------------

#spring.cache.type=redis
#spring.data.redis.host=13.232.52.254
#spring.data.redis.port=6379
#spring.data.redis.password=AWSs3123
#spring.cache.redis.time-to-live=600000 # 10 mins TTL

#----------------------------------------

server.port=8108
spring.datasource.url=jdbc:mysql://localhost:3306/newadmission?ServerTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pooja@2002
client.superadmin.base-url=http://localhost:8106

#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.redis.time-to-live=600000


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



# ================= JWT Configuration =================
jwt.secret=s3cR3tK3y!@#4567890qwertyuiopasdfgh
jwt.expiration=86400000
internal.jwt.secret=s3cR3tK3y!@#4567890qwertyuiopasdfgh




# AWS S3 Configuration
aws.access-key=AKIA33IBOOI4K6F6U4DJ
aws.secret-key=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
aws.s3.bucket-name=attendace-docs
aws.region=ap-south-1



#email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info.pjsofttech@gmail.com
spring.mail.password=wtok telq zpaj dzhg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Gupshup WhatsApp Configuration
gupshup.whatsapp.api-key=sk_6851acdd47ce4f04b060a7bb6932f61c
gupshup.whatsapp.url=https://api.gupshup.io/wa/api/v1/template/msg
gupshup.source.whatsapp=919371888101

# Gupshup SMS Configuration
gupshup.sms.api-key=nl41kell7w4ws21jvezx28et0dnpqgh5
gupshup.sms.url=https://api.gupshup.io/sm/api/v1/msg
gupshup.source.sms=PJSOFT

# Application Name
gupshup.app.name=pjsofttechwhatsapp



admission.attendance.python-api-login-url=https://pjsofttech.in:51443/auto-branch-scan
admission.attendance.python-api-logout-url=https://pjsofttech.in:51443/auto-branch-scan


spring.output.ansi.enabled=ALWAYS